apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-handler
  labels:
    cloud.googleapis.com/location: europe-west4
spec:
  template:
    spec:
      containers:
        - image: europe-west4-docker.pkg.dev/personal-website-264919/aandevski-dev-image-repo/api-handler
        - env:
            - name: GLOG_log_dir
              value: /var/log
