name: Bazel
on:
  push:
    branches:
      - main
    paths:
      - "api_handler/**"
      - "proto/**"
      - "WORKSPACE"
      - ".github/workflows/bazel.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: l.gcr.io/google/bazel
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
  push:
    name: Push API Handler Image
    runs-on: ubuntu-latest
    container:
      image: l.gcr.io/google/bazel
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.SA_GITHUB_IMAGE_PUSHER_CREDS }}
      - run: bazel run //api_handler:api_handler_image_push
