name: Bazel
on:
  push:
    branches:
      - main
    paths:
      - "api_handler/**"
      - "proto/**"
      - "WORKSPACE"
      - ".github/workflows/bazel.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: aandevski/build-img:latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
  push:
    name: Push API Handler Image
    runs-on: ubuntu-latest
    container:
      image: aandevski/build-img:latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bazel run //api_handler:api_handler_image_push
