name: Static
on:
  push:
    branches:
      - main
    paths:
      - "static/**"
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.SA_GITHUB_STATIC_UPLOADER_CREDS }}
          path: static
          destination: aandevski.dev
          parent: false
