name: Static
on:
  push:
    branches:
      - main
jobs:
  upload:
    name: Upload
    steps:
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.SA_GITHUB_STATIC_UPLOADER_CREDS }}
          path: static
          destination: aandevski.dev
          parent: false
